
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SajalSaha
 */
public class Student_Details extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Student_Details.class.getName());
 
    /**
     * Creates new form Student_Details
     */Connection con;
 Statement stmt;
 ResultSet rs;
 FormFrame form;
 public Student_Details() {
    initComponents();
    connect();
}
    public Student_Details(FormFrame form) {
        initComponents();
        connect();
        this.form=form;
    }
    public void connect()
{
try
{DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmanagement","root","");
stmt=con.createStatement();
rs=stmt.executeQuery("select * from std");
while(rs.next()){
model.addRow(new Object[]{rs.getString("Sid"),
rs.getString("Fname"),
rs.getString("Lname"),
rs.getString("Class"),
rs.getString("Year"),
rs.getString("Dob"),
rs.getString("Contact"),
rs.getString("email"),
rs.getString("Gender"),
rs.getString("P_Add"),
rs.getString("Pr_Add")
} );}
con.close();
}
catch(Exception ex)
{
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Details");

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SID", "F_NAME", "L_NAME", "CLASS", "YEAR", "DOB", "CONTACT", "EMAIL", "GENDER", "P-ADDRESS", "P-ADDRESS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                
       
  int i = jTable1.getSelectedRow();
  String Sid = jTable1.getValueAt(i,0).toString();
  String Fname = jTable1.getValueAt(i, 1).toString();
  String Lname = jTable1.getValueAt(i, 2).toString();
  String Class = jTable1.getValueAt(i, 3).toString();
  String Year = jTable1.getValueAt(i, 4).toString();
  String Dob = jTable1.getValueAt(i, 5).toString();
  String Contact = jTable1.getValueAt(i, 6).toString();
  String email = jTable1.getValueAt(i, 7).toString();
  String P_Add = jTable1.getValueAt(i, 8).toString();
  String Pr_Add = jTable1.getValueAt(i, 9).toString();
  
 // TODO add your handling code here:
    }                               

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Add_Student_Data obj=new Add_Student_Data("jButton3");

obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 DefaultTableModel model=   (DefaultTableModel)jTable1.getModel();  
 int i= jTable1.getSelectedRow(); 
  if (i>=0){
      String Sid = jTable1.getValueAt(i,0).toString();
  String Fname = jTable1.getValueAt(i, 1).toString();
  String Lname = jTable1.getValueAt(i, 2).toString();
  String Class = jTable1.getValueAt(i, 3).toString();
  String Year = jTable1.getValueAt(i, 4).toString();
  String Dob = jTable1.getValueAt(i, 5).toString();
  String Contact = jTable1.getValueAt(i, 6).toString();
  String email = jTable1.getValueAt(i, 7).toString();
   String Gender = jTable1.getValueAt(i, 8).toString();
  String P_Add = jTable1.getValueAt(i, 9).toString();
  String Pr_Add = jTable1.getValueAt(i, 10).toString();
      Add_Student_Data obj1 = new Add_Student_Data("jButton4");
        obj1.st1.setText(Sid);
        obj1.st2.setText(Fname);
        obj1.st3.setText(Lname);
        obj1.st4.setText(Class);
        obj1.st5.setText(Year);
        try {
    Date date = new SimpleDateFormat("dd MMM yyyy").parse(Dob);
    obj1.st6.setDate(date);
} catch (Exception e) {
    e.printStackTrace();
}
        obj1.st7.setText(Contact);
        obj1.st8.setText(email);
        obj1.st9.setText(P_Add);
        obj1.st10.setText(Pr_Add);
        if(Gender.equals("M")){
 obj1.sr1.setSelected(true);
}else if(Gender.equals("F")){
obj1.sr2.setSelected(true);}
else if(Gender.equals("T")){
obj1.sr3.setSelected(true);}
     obj1.setVisible(true);}
  else{JOptionPane.showMessageDialog(this,"Select row atfirst","Error",JOptionPane.ERROR_MESSAGE);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                            
    
    int i = jTable1.getSelectedRow();

    if(i >= 0)
    {
        String Sid = jTable1.getValueAt(i, 0).toString();

        try
        {
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/schoolmanagement",
                "root",
                ""
            );

            String sql = "DELETE FROM std WHERE Sid=?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, Sid);

            int x = pst.executeUpdate();

            if(x > 0)
            {
                JOptionPane.showMessageDialog(this, "Row Deleted Successfully");
                
                // remove from table model also
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(i);
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(this, "Please select a row first");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Student_Details().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
