
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SajalSaha
 */
public class Calculator1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator1.class.getName());
double num1=0,num2=0;
String op = null;

    /**
     * Creates new form Calculator1
     */
    public Calculator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        n1 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        powr = new javax.swing.JButton();
        div = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        n10 = new javax.swing.JButton();

        jButton15.setText("jButton1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        t1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        n1.setBackground(new java.awt.Color(51, 51, 51));
        n1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n1.setForeground(new java.awt.Color(255, 255, 255));
        n1.setText("1");
        n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n1MouseReleased(evt);
            }
        });
        n1.addActionListener(this::n1ActionPerformed);

        n4.setBackground(new java.awt.Color(51, 51, 51));
        n4.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n4.setForeground(new java.awt.Color(255, 255, 255));
        n4.setText("4");
        n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n4MouseReleased(evt);
            }
        });
        n4.addActionListener(this::n4ActionPerformed);

        n7.setBackground(new java.awt.Color(51, 51, 51));
        n7.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n7.setForeground(new java.awt.Color(255, 255, 255));
        n7.setText("7");
        n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n7MouseReleased(evt);
            }
        });
        n7.addActionListener(this::n7ActionPerformed);

        Back.setBackground(new java.awt.Color(51, 51, 51));
        Back.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BackMouseReleased(evt);
            }
        });
        Back.addActionListener(this::BackActionPerformed);

        n0.setBackground(new java.awt.Color(51, 51, 51));
        n0.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n0.setForeground(new java.awt.Color(255, 255, 255));
        n0.setText("0");
        n0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n0MouseReleased(evt);
            }
        });
        n0.addActionListener(this::n0ActionPerformed);

        n8.setBackground(new java.awt.Color(51, 51, 51));
        n8.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n8.setForeground(new java.awt.Color(255, 255, 255));
        n8.setText("8");
        n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n8MouseReleased(evt);
            }
        });
        n8.addActionListener(this::n8ActionPerformed);

        n5.setBackground(new java.awt.Color(51, 51, 51));
        n5.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n5.setForeground(new java.awt.Color(255, 255, 255));
        n5.setText("5");
        n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n5MouseReleased(evt);
            }
        });
        n5.addActionListener(this::n5ActionPerformed);

        n2.setBackground(new java.awt.Color(51, 51, 51));
        n2.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n2.setForeground(new java.awt.Color(255, 255, 255));
        n2.setText("2");
        n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n2MouseReleased(evt);
            }
        });
        n2.addActionListener(this::n2ActionPerformed);

        n3.setBackground(new java.awt.Color(51, 51, 51));
        n3.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n3.setForeground(new java.awt.Color(255, 255, 255));
        n3.setText("3");
        n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n3MouseReleased(evt);
            }
        });
        n3.addActionListener(this::n3ActionPerformed);

        n6.setBackground(new java.awt.Color(51, 51, 51));
        n6.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n6.setForeground(new java.awt.Color(255, 255, 255));
        n6.setText("6");
        n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n6MouseReleased(evt);
            }
        });
        n6.addActionListener(this::n6ActionPerformed);

        n9.setBackground(new java.awt.Color(51, 51, 51));
        n9.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n9.setForeground(new java.awt.Color(255, 255, 255));
        n9.setText("9");
        n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n9MouseReleased(evt);
            }
        });
        n9.addActionListener(this::n9ActionPerformed);

        clean.setBackground(new java.awt.Color(51, 51, 51));
        clean.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        clean.setForeground(new java.awt.Color(255, 255, 255));
        clean.setText("C");
        clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cleanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cleanMouseReleased(evt);
            }
        });
        clean.addActionListener(this::cleanActionPerformed);

        Equal.setBackground(new java.awt.Color(51, 51, 51));
        Equal.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        Equal.setForeground(new java.awt.Color(255, 255, 255));
        Equal.setText("=");
        Equal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EqualMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EqualMouseReleased(evt);
            }
        });
        Equal.addActionListener(this::EqualActionPerformed);

        powr.setBackground(new java.awt.Color(51, 51, 51));
        powr.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        powr.setForeground(new java.awt.Color(255, 255, 255));
        powr.setText("^");
        powr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                powrMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                powrMouseReleased(evt);
            }
        });
        powr.addActionListener(this::powrActionPerformed);

        div.setBackground(new java.awt.Color(51, 51, 51));
        div.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("/");
        div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                divMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divMouseReleased(evt);
            }
        });
        div.addActionListener(this::divActionPerformed);

        mult.setBackground(new java.awt.Color(51, 51, 51));
        mult.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        mult.setForeground(new java.awt.Color(255, 255, 255));
        mult.setText("x");
        mult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                multMouseReleased(evt);
            }
        });
        mult.addActionListener(this::multActionPerformed);

        sub.setBackground(new java.awt.Color(51, 51, 51));
        sub.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setText("-");
        sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                subMouseReleased(evt);
            }
        });
        sub.addActionListener(this::subActionPerformed);

        sum.setBackground(new java.awt.Color(51, 51, 51));
        sum.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        sum.setForeground(new java.awt.Color(255, 255, 255));
        sum.setText("+");
        sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sumMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sumMouseReleased(evt);
            }
        });
        sum.addActionListener(this::sumActionPerformed);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculator");

        n10.setBackground(new java.awt.Color(51, 51, 51));
        n10.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        n10.setForeground(new java.awt.Color(255, 255, 255));
        n10.setText(".");
        n10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                n10MouseReleased(evt);
            }
        });
        n10.addActionListener(this::n10ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(n7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(n1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(n4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(n0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(n10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(powr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(div, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
 String a= "1";
 t1.setText(t1.getText() + a);
      // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
    String a= "2";
 t1.setText(t1.getText() +a);
          // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
String a= "3";
 t1.setText(t1.getText() +a);
 // TODO add your handling code here:
    }//GEN-LAST:event_n3ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
String a= "4";
 t1.setText(t1.getText() +a);
            // TODO add your handling code here:
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
String a= "5";
 t1.setText(t1.getText() +a);

    }//GEN-LAST:event_n5ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
String a= "6";
 t1.setText(t1.getText() +a);
// TODO add your handling code here:
    }//GEN-LAST:event_n6ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
String a= "7";
 t1.setText(t1.getText() +a);
// TODO add your handling code here:
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
String a= "8";
 t1.setText(t1.getText() +a);
// TODO add your handling code here:
    }//GEN-LAST:event_n8ActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
String a= "9";
 t1.setText(t1.getText() +a);
// TODO add your handling code here:
    }//GEN-LAST:event_n9ActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
String a= "0";
 t1.setText(t1.getText() +a);
// TODO add your handling code here:
    }//GEN-LAST:event_n0ActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
     num1=Double.parseDouble(t1.getText());
        t1.setText("");
        op="+";// TODO add your handling code here:
    }//GEN-LAST:event_sumActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
      t1.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_cleanActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
       num1=Double.parseDouble(t1.getText());
        t1.setText("");
        op="-";   // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
 num1=Double.parseDouble(t1.getText());
        t1.setText("");
        op="x";         // TODO add your handling code here:
    }//GEN-LAST:event_multActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
 num1=Double.parseDouble(t1.getText());
        t1.setText("");
        op="/";        // TODO add your handling code here:
    }//GEN-LAST:event_divActionPerformed

    private void powrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrActionPerformed
 num1=Double.parseDouble(t1.getText());
        t1.setText("");
        op="^";        // TODO add your handling code here:
    }//GEN-LAST:event_powrActionPerformed

    private void EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualActionPerformed
num2=Double.parseDouble(t1.getText());
double ans=0;
 if ("+".equals(op)) {
    ans = num1+num2;}
 if("-".equals(op)){
ans = num1-num2;}
 if("x".equals(op)){
ans = num1*num2;}
 if("/".equals(op)){
ans = num1/num2;}
if("^".equals(op)) {
ans = Math.pow(num1,num2);}
t1.setText(""+ans);
op=null;

    }//GEN-LAST:event_EqualActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
String str=t1.getText();
t1.setText(str.substring(0,str.length()-1));// TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void n1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MousePressed
     n1.setForeground(Color.yellow);   // TODO add your handling code here:
    }//GEN-LAST:event_n1MousePressed

    private void n1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n1MouseReleased
       n1.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n1MouseReleased

    private void n2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MousePressed
      n2.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n2MousePressed

    private void n2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n2MouseReleased
        n2.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n2MouseReleased

    private void n3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MousePressed
      n3.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n3MousePressed

    private void n3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n3MouseReleased
         n3.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_n3MouseReleased

    private void n4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MousePressed
      n4.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n4MousePressed

    private void n4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n4MouseReleased
        n4.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n4MouseReleased

    private void n5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MousePressed
      n5.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n5MousePressed

    private void n5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n5MouseReleased
        n5.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n5MouseReleased

    private void n6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MousePressed
      n6.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n6MousePressed

    private void n6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n6MouseReleased
        n6.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n6MouseReleased

    private void n7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MousePressed
      n7.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n7MousePressed

    private void n7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n7MouseReleased
      n7.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_n7MouseReleased

    private void n8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MousePressed
      n8.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n8MousePressed

    private void n8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n8MouseReleased
        n8.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n8MouseReleased

    private void n9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MousePressed
      n9.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n9MousePressed

    private void n9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n9MouseReleased
         n9.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_n9MouseReleased

    private void n0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MousePressed
      n0.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n0MousePressed

    private void n0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n0MouseReleased
        n0.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_n0MouseReleased

    private void sumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumMousePressed
      sum.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_sumMousePressed

    private void sumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumMouseReleased
       sum.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_sumMouseReleased

    private void subMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMousePressed
      sub.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_subMousePressed

    private void subMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMouseReleased
       sub.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_subMouseReleased

    private void multMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multMousePressed
       mult.setForeground(Color.yellow); // TODO add your handling code here:
    }//GEN-LAST:event_multMousePressed

    private void multMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multMouseReleased
      mult.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_multMouseReleased

    private void divMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMousePressed
      div.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_divMousePressed

    private void divMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMouseReleased
       div.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_divMouseReleased

    private void powrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powrMousePressed
       powr.setForeground(Color.yellow); // TODO add your handling code here:
    }//GEN-LAST:event_powrMousePressed

    private void powrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powrMouseReleased
      powr.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_powrMouseReleased

    private void EqualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqualMousePressed
     Equal.setForeground(Color.yellow);   // TODO add your handling code here:
    }//GEN-LAST:event_EqualMousePressed

    private void EqualMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EqualMouseReleased
     Equal.setForeground(Color.white);   // TODO add your handling code here:
    }//GEN-LAST:event_EqualMouseReleased

    private void cleanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMousePressed
      clean.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_cleanMousePressed

    private void cleanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseReleased
       clean.setForeground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_cleanMouseReleased

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
      Back.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_BackMousePressed

    private void BackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseReleased
      Back.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseReleased

    private void n10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n10MousePressed
       n10.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_n10MousePressed

    private void n10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n10MouseReleased
        n10.setForeground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_n10MouseReleased

    private void n10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n10ActionPerformed
        String a= ".";
 t1.setText(t1.getText() + a); // TODO add your handling code here:
    }//GEN-LAST:event_n10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Equal;
    private javax.swing.JButton clean;
    private javax.swing.JButton div;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mult;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n10;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton powr;
    private javax.swing.JButton sub;
    private javax.swing.JButton sum;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
